#:kivy 1.8.0

<KetchuporoLayout>:
    orientation: "vertical"

<WelcomeWidget>:
    orientation: "vertical"
    Label:
        font_size: 70
        text: "no elo"
    Button:
        text: "Start!"
        on_release: root.start()

<TimerWidget>:
    orientation: "vertical"
    Label:
        font_size: 70
        text: root.model.timer_label
    Label:
        font_size: 70
        text: str(root.model.pomodoros_counter)
